name: build-and-push

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-hugo-site:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'public' || 'preview' }}
      url: ${{ steps.create-env-vars.outputs.url }}

    steps:
      - name: Checkout site
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.129.0"
          extended: true

      - name: Build site
        run: hugo

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}

      - name: Construct environment variables
        id: create-env-vars
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/master" ]]; then
            PR_ID=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "S3_PREFIX=$PR_ID/" >> "$GITHUB_ENV"
            echo "url=https://$PR_ID.${{ vars.SITE_URL }}" >> "$GITHUB_OUTPUT"
          else
            echo "url=https://${{ vars.SITE_URL }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Push to S3
        run: |
          aws s3 rm \
            ${{ secrets.AWS_S3_BUCKET }}/${{ env.S3_PREFIX }} --recursive
          aws s3 sync \
            ./public ${{ secrets.AWS_S3_BUCKET }}/${{ env.S3_PREFIX }}

      - name: Invalidate CloudFront cache
        if: github.ref == 'refs/heads/master' && success()
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"