name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pre-commit
        run: pip install pre-commit
        shell: bash

      - name: Cache pre-commit environment
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/R
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash